# Generated by Django 3.0.6 on 2020-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cian_id', models.CharField(max_length=512)),
                ('avito_id', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=512)),
                ('area', models.CharField(max_length=512)),
                ('floor', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=512)),
                ('ceiling_height', models.CharField(max_length=512)),
                ('water_closet', models.CharField(max_length=512)),
                ('balcony', models.CharField(max_length=512)),
                ('renovation', models.CharField(max_length=512)),
                ('view_from_windows', models.CharField(max_length=512)),
                ('kitchen_area', models.CharField(max_length=512)),
                ('living_area', models.CharField(max_length=512)),
                ('built_in', models.CharField(max_length=512)),
                ('plan', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
