# Generated by Django 3.0.6 on 2020-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='building_info',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='offer',
            name='raw_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='area',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='avito_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='balcony',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='built_in',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ceiling_height',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cian_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='floor',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kitchen_area',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='living_area',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='plan',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='renovation',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='view_from_windows',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='offer',
            name='water_closet',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
