# Generated by Django 3.0.6 on 2020-05-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0003_auto_20200504_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='house_type',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='rooms',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
