# Generated by Django 2.2.3 on 2020-05-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0005_auto_20200504_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='price',
            new_name='price_old',
        ),
    ]
