# Generated by Django 2.2.3 on 2020-05-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0006_auto_20200504_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='raw_price',
            new_name='price',
        ),
    ]
