# Generated by Django 2.2.3 on 2020-05-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0008_remove_offer_price_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, default='Квартира', max_length=512, null=True),
        ),
    ]
