# Generated by Django 2.2.3 on 2020-05-04 22:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0009_auto_20200504_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='built_in',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Год строительства'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='floor',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kitchen_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь кухни'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='living_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, default='Квартира', max_length=512, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='old_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None, verbose_name='Предыдущие цены'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
