# Generated by Django 2.2.3 on 2020-05-05 08:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0010_auto_20200504_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('price_change', models.CharField(blank=True, max_length=512, null=True, verbose_name='Изменение цены')),
                ('price_per_sq_change', models.CharField(blank=True, max_length=512, null=True, verbose_name='Изменение цены за м²')),
                ('price_per_sq', models.FloatField(blank=True, null=True, verbose_name='Цена за м²')),
                ('interesting_offers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), blank=True, null=True, size=None, verbose_name='Старая цена')),
            ],
            options={
                'db_table': 'statistic',
            },
        ),
        migrations.AlterField(
            model_name='offer',
            name='built_in',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='old_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None, verbose_name='Старая цена'),
        ),
    ]
