# Generated by Django 2.2.3 on 2020-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0011_auto_20200505_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за м²'),
        ),
    ]
