# Generated by Django 2.2.3 on 2020-05-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0012_statistic_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='url',
            new_name='avito_url',
        ),
        migrations.AddField(
            model_name='offer',
            name='address_location',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='cian_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='price_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение цены'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='price_per_sq_change',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение цены за м²'),
        ),
    ]
