# Generated by Django 2.2.3 on 2020-05-06 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0013_auto_20200506_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='old_prices',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
        migrations.AddField(
            model_name='offer',
            name='avito_old_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None, verbose_name='Старая цена Avito'),
        ),
        migrations.AddField(
            model_name='offer',
            name='avito_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена Avito'),
        ),
        migrations.AddField(
            model_name='offer',
            name='cian_old_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None, verbose_name='Старая цена Cian'),
        ),
        migrations.AddField(
            model_name='offer',
            name='cian_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена Cian'),
        ),
    ]
