# Generated by Django 2.2.10 on 2020-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0014_auto_20200506_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='address_location',
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
