# Generated by Django 2.2.10 on 2020-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0015_auto_20200506_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='avito_new',
            field=models.ManyToManyField(related_name='avito_new', to='vlg_parser.Offer'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='cian_new',
            field=models.ManyToManyField(related_name='cian_new', to='vlg_parser.Offer'),
        ),
    ]
