# Generated by Django 2.2.10 on 2020-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0017_auto_20200506_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='interesting_offers',
        ),
        migrations.AddField(
            model_name='statistic',
            name='interesting_offers',
            field=models.ManyToManyField(related_name='interesting', to='vlg_parser.Offer'),
        ),
    ]
