# Generated by Django 2.2.10 on 2020-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlg_parser', '0018_auto_20200512_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
